# Generated by Django 4.2.7 on 2023-11-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Employee',
        ),
    ]
